import { useSession } from "next-auth/react";
import Head from "next/head";

import { api } from "~/utils/api";
import Todos from "~/components/Todos";
import CreateTodo from "~/components/CreateTodo";
import '@mantine/core/styles.css';
import '@mantine/notifications/styles.css';

export default function Home() {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Full Stack App Todo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          {
            sessionData && (
              <div className="grid grid-cols-1 gap-4 md:gap-8">
                <div className="flex flex-col gap-4 rounded-xl bg-white/10 p-8 px-16 text-white">
                  <h3 className="text-xl font-bold text-center">To do list</h3>
                  <Todos />
                  <CreateTodo />
                </div>
              </div>
            )
          }
          {
            !sessionData && (
              <div className="text-center">
                <h1 className="text-4xl font-bold text-white mb-4">Bienvenido a Todo App</h1>
                <p className="text-xl text-white/80 mb-8">Inicia sesión para comenzar a gestionar tus tareas</p>
              </div>
            )
          }
        </div>
      </main>
    </>
  );
}